# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts
COPY tsconfig.json .
COPY src ./src
RUN npm install typescript --no-save && npx tsc
CMD ["node","dist/index.js"]
